# .goreleaser.yaml
version: 2


project_name: nexus-v


before:
  hooks:
    - go mod tidy


builds:
  - id: archive
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/nexus-v
    binary: nexus-v


  - id: raw
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/nexus-v
    binary: nexus-v_{{ .Os }}_{{ .Arch }}
