name: Stale Management
on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  stale:
    uses: stillsystems/.github/.github/workflows/reusable-stale.yml@main
    permissions:
      issues: write
      pull-requests: write
