name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  go-ci:
    uses: stillsystems/.github/.github/workflows/reusable-go-ci.yml@main
    with:
      go-version: '1.24.2'

  node-ci:
    uses: stillsystems/.github/.github/workflows/reusable-node-ci.yml@main
    with:
      node-version: '20'
      working-directory: 'nexus-v-vscode'
