name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'
          check-latest: true
      - name: Lint
        env:
          GOTOOLCHAIN: auto
        run: go vet ./...
      - name: Test
        env:
          GOTOOLCHAIN: auto
        run: go test ./...

  test-vscode:
    name: Build VS Code Extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        working-directory: nexus-v-vscode
        run: npm install
      - name: Build
        working-directory: nexus-v-vscode
        run: npm run build
